<a href="https://colab.research.google.com/github/imeesam/Word_embedding_using_keras/blob/main/Word_embedding_using_keras_embedding_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = [
    'nice food',
    'amazing resturant',
    'too good',
    'just loved it!',
    'will go again',
    'horrible food',
    'never go there',
    'poor serivce',
    'poor quality',
    'needs improvement'
]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [17]:
vocab_size = 50
review = 'amazing resturant'
one_hot(review , vocab_size ) # review and vocab size

[11, 42]

In [18]:
encoded_reviews =  [one_hot(i, vocab_size) for i in reviews]
encoded_reviews

[[5, 20],
 [11, 42],
 [36, 37],
 [46, 12, 24],
 [26, 48, 10],
 [14, 20],
 [37, 48, 29],
 [24, 5],
 [24, 44],
 [14, 17]]

In [19]:
 max_length = 3
 padded_reviews = pad_sequences(encoded_reviews, maxlen = max_length , padding = 'post')
 padded_reviews

array([[ 5, 20,  0],
       [11, 42,  0],
       [36, 37,  0],
       [46, 12, 24],
       [26, 48, 10],
       [14, 20,  0],
       [37, 48, 29],
       [24,  5,  0],
       [24, 44,  0],
       [14, 17,  0]], dtype=int32)

In [20]:
emmbbed_vector_size =  4
model = Sequential()
model.add(Embedding(vocab_size,emmbbed_vector_size, input_length = max_length, name = 'embedding'))
model.add(Flatten())
model.add(Dense(1,activation = 'sigmoid'))

In [21]:
X =  padded_reviews
y = sentiment

In [22]:
model.compile(optimizer = 'adam',loss = 'binary_crossentropy', metrics = ['accuracy'] )
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.fit(X,y,epochs = 30 ,verbose = 0 )

In [24]:
loss , acc = model.evaluate(X,y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 191ms/step - accuracy: 0.8000 - loss: 0.6489


In [25]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [26]:
weights[17]

array([ 0.02944737, -0.04752451,  0.04104374, -0.0345642 ], dtype=float32)

In [27]:
weights[3]

array([ 0.00235008, -0.02973101, -0.03123162, -0.009979  ], dtype=float32)